---

- name: give credits
  debug: 
    msg: "this was inspired from http://www.socsci.uci.edu/~jstern/uci_vpn_ubuntu/ubuntu-openconnect-uci-instructions.html"

- name: install packages
  package:
    name: "{{ item }}"
    state: "installed"
  with_items: 
  - openconnect 
  - openvpn

- name: install script binary
  template:
    src: "{{ openconnect_script_template }}"
    dest: "{{ openconnect_script_dest }}"
    mode: 0755
